//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("ServiceLifeController")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Behzad Khosravifar 2016")]
[assembly: System.Reflection.AssemblyTrademark("Shoniz")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("1.5.52")]
[assembly: System.Reflection.AssemblyFileVersion("1.5.52")]
[assembly: System.Reflection.AssemblyInformationalVersion("Compiled By Behzad")]