//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManager.SmsService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsService.smsSoap")]
    public interface smsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doSendArraySMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] doSendArraySMS(string uUsername, string uPassword, string uNumber, string[] uCellphone, string[] uMessage, bool[] uFarsi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doSendArraySMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> doSendArraySMSAsync(string uUsername, string uPassword, string uNumber, string[] uCellphone, string[] uMessage, bool[] uFarsi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doSendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string doSendSMS(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doSendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> doSendSMSAsync(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string doReceiveSMS(string uUsername, string uPassword, long uLastRowID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> doReceiveSMSAsync(string uUsername, string uPassword, long uLastRowID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMSDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet doReceiveSMSDS(string uUsername, string uPassword, long uLastRowID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMSDS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> doReceiveSMSDSAsync(string uUsername, string uPassword, long uLastRowID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMSAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string doReceiveSMSAll(string uUsername, string uPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMSAll", ReplyAction="*")]
        System.Threading.Tasks.Task<string> doReceiveSMSAllAsync(string uUsername, string uPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMSAllDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet doReceiveSMSAllDS(string uUsername, string uPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMSAllDS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> doReceiveSMSAllDSAsync(string uUsername, string uPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getDelivery(string uUsername, string uReturnIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getDeliveryAsync(string uUsername, string uReturnIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryOlder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getDeliveryOlder(string uUsername, string uReturnIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryOlder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getDeliveryOlderAsync(string uUsername, string uReturnIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getInfo(string uUsername, string uPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getInfoAsync(string uUsername, string uPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsSoapChannel : SmsManager.SmsService.smsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsSoapClient : System.ServiceModel.ClientBase<SmsManager.SmsService.smsSoap>, SmsManager.SmsService.smsSoap {
        
        public smsSoapClient() {
        }
        
        public smsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string[] doSendArraySMS(string uUsername, string uPassword, string uNumber, string[] uCellphone, string[] uMessage, bool[] uFarsi) {
            return base.Channel.doSendArraySMS(uUsername, uPassword, uNumber, uCellphone, uMessage, uFarsi);
        }
        
        public System.Threading.Tasks.Task<string[]> doSendArraySMSAsync(string uUsername, string uPassword, string uNumber, string[] uCellphone, string[] uMessage, bool[] uFarsi) {
            return base.Channel.doSendArraySMSAsync(uUsername, uPassword, uNumber, uCellphone, uMessage, uFarsi);
        }
        
        public string doSendSMS(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi) {
            return base.Channel.doSendSMS(uUsername, uPassword, uNumber, uCellphones, uMessage, uFarsi);
        }
        
        public System.Threading.Tasks.Task<string> doSendSMSAsync(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi) {
            return base.Channel.doSendSMSAsync(uUsername, uPassword, uNumber, uCellphones, uMessage, uFarsi);
        }
        
        public string doReceiveSMS(string uUsername, string uPassword, long uLastRowID) {
            return base.Channel.doReceiveSMS(uUsername, uPassword, uLastRowID);
        }
        
        public System.Threading.Tasks.Task<string> doReceiveSMSAsync(string uUsername, string uPassword, long uLastRowID) {
            return base.Channel.doReceiveSMSAsync(uUsername, uPassword, uLastRowID);
        }
        
        public System.Data.DataSet doReceiveSMSDS(string uUsername, string uPassword, long uLastRowID) {
            return base.Channel.doReceiveSMSDS(uUsername, uPassword, uLastRowID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> doReceiveSMSDSAsync(string uUsername, string uPassword, long uLastRowID) {
            return base.Channel.doReceiveSMSDSAsync(uUsername, uPassword, uLastRowID);
        }
        
        public string doReceiveSMSAll(string uUsername, string uPassword) {
            return base.Channel.doReceiveSMSAll(uUsername, uPassword);
        }
        
        public System.Threading.Tasks.Task<string> doReceiveSMSAllAsync(string uUsername, string uPassword) {
            return base.Channel.doReceiveSMSAllAsync(uUsername, uPassword);
        }
        
        public System.Data.DataSet doReceiveSMSAllDS(string uUsername, string uPassword) {
            return base.Channel.doReceiveSMSAllDS(uUsername, uPassword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> doReceiveSMSAllDSAsync(string uUsername, string uPassword) {
            return base.Channel.doReceiveSMSAllDSAsync(uUsername, uPassword);
        }
        
        public string getDelivery(string uUsername, string uReturnIDs) {
            return base.Channel.getDelivery(uUsername, uReturnIDs);
        }
        
        public System.Threading.Tasks.Task<string> getDeliveryAsync(string uUsername, string uReturnIDs) {
            return base.Channel.getDeliveryAsync(uUsername, uReturnIDs);
        }
        
        public string getDeliveryOlder(string uUsername, string uReturnIDs) {
            return base.Channel.getDeliveryOlder(uUsername, uReturnIDs);
        }
        
        public System.Threading.Tasks.Task<string> getDeliveryOlderAsync(string uUsername, string uReturnIDs) {
            return base.Channel.getDeliveryOlderAsync(uUsername, uReturnIDs);
        }
        
        public string getInfo(string uUsername, string uPassword) {
            return base.Channel.getInfo(uUsername, uPassword);
        }
        
        public System.Threading.Tasks.Task<string> getInfoAsync(string uUsername, string uPassword) {
            return base.Channel.getInfoAsync(uUsername, uPassword);
        }
    }
}
